name: Android Unit Tests (Self-hosted)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  unit:
    name: Run unit tests (JVM)
    runs-on: [self-hosted]   # <— uses your machine, no billed minutes
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # You can still use setup-java on self-hosted
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable (no-op on Windows)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
