name: Android Unit Tests

on:
  push:
    branches: [ front-end-update ]
  pull_request:
    branches: [ front-end-update ]
  workflow_dispatch:

# Avoid running multiple concurrent jobs on the same ref
concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Run unit tests (JVM)
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 👉 Runs ONLY JVM unit tests under src/test (no emulator)
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon --warning-mode all

      # Always upload HTML reports + JUnit XML so you can inspect failures
      - name: Upload unit test HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest

      - name: Upload JUnit XML results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-xml
          path: |
            **/build/test-results/testDebugUnitTest/*.xml
            **/build/test-results/test/*.xml
