name: Android Unit Tests

on:
  push:
    branches: [ fron-end-update ]
  pull_request:
    branches: [ fron-end-update ]
  workflow_dispatch:

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run unit tests (JVM)
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
